### ISSUE TITLE
Monsters spawn at daytime

### ISSUE THREAD

**Issue by tjespe** [RevivalPMMP/PureEntitiesX#33]
On my server, monsters (zombies, skeletons, spiders, creepers, endermen, et.c.) spawn even though it is in the middle of the day.
I don't know if this is a bug or if it is something you haven't yet implemented, however I can't imagine that it is very hard to fix. Checking light conditions may be tricky, but just checking the time to see whether it's day or not would be better than how it currently is.
Then again, I haven't looked so carefully at your code, so I don't know if you actually have implemented this or if what I am experiencing is just a bug.

**Comment by Sandertv** [comment]
Have you made sure you're using the latest version? I've fixed this a day or 2 ago, so it should work.

**Comment by tjespe** [comment]
I'm using GitHub Desktop to sync with your repository, so yes it is the latest version.

**Comment by tjespe** [comment]
If it's relevant I am using PocketMine on an iMac with macOS Sierra 10.12.1

**Comment by Sandertv** [comment]
Do you have any factors that might somehow impact the spawning? Maybe an imported world, or something else?

**Comment by tjespe** [comment]
The world is created in the official Minecraft for mac app, and copied into the worlds directory.

**Comment by tjespe** [comment]
My `server.properties` file might be relevant:

`#Properties Config file
#Thu Dec 15 16:17:28 CET 2016
server-name=Beste server
server-port=19133
gamemode=0
max-players=20
spawn-protection=-1
white-list=0
enable-query=off
enable-rcon=on
rcon.password=Vc44GzjQEF
motd=Minecraft: PE Server
announce-player-achievements=on
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=3
generator-settings=
level-name=k4
level-seed=
level-type=DEFAULT
auto-save=on
`

**Comment by Sandertv** [comment]
Would you mind trying to generate a new world using the PocketMine world generator and try to reproduce this there too?

**Comment by tjespe** [comment]
Okay, I'll try

**Comment by Sandertv** [comment]
Just tried reproducing and you're right. They don't spawn the whole day, but they spawn while the sun isn't even close to setting yet. I'll fix this shortly.

**Comment by tjespe** [comment]
This is a completely different issue but all of sudden I am unable to use the plugin. When starting the server I get this error:

`[16:54:06] [Server thread/INFO]: Loading source plugin PureEntitiesX v1.1`

`[16:54:06] [Server thread/CRITICAL]: ClassNotFoundException: "Class revivalpmmp\pureentities\entity\monster\WalkingMonster not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144`

`[16:54:06] [Server thread/INFO]: Disabling DevTools v1.11.0`

I've doublechecked that the `WalkingMonster.php` file exists so I have no idea why this error occurs. Everything worked a few moments ago.
Anyway I'm unable to try to reproduce the error we talked about because I'm suddenly unable to load the plugin...

**Comment by tjespe** [comment]
Okay, that's great

**Comment by Sandertv** [comment]
Oh yikes, something went wrong with the namespace changing from @Magicode1

**Comment by tjespe** [comment]
Oh I see

**Comment by Sandertv** [comment]
Okay hopefully it's fixed now.

**Comment by tjespe** [comment]
Getting a different error now, but still unable to load the plugin:
`[17:10:30] [Server thread/CRITICAL]: ClassNotFoundException: "Class magicode\pureentities\PluginBase not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144`

**Comment by tjespe** [comment]
The name `magicode` is still used PureEntities.php on line 79, in CreatureSpawnEvent.php on line 3 and in Spawner.php on line 3, 5 and 6 if that helps you fix it

**Comment by Sandertv** [comment]
Thanks a lot! It should work now (hopefully :P)

**Comment by tjespe** [comment]
Hmm, still doesn't work although I have synced and your changes are applied:
`[17:20:55] [Server thread/CRITICAL]: ClassNotFoundException: "Class revivalpmmp\pureentities\PluginBase not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144`
At least the name `revivalpmmp` is in the error now

**Comment by caspervanneck** [comment]
@tjespe  uhm yhere is somting rong

**Comment by Sandertv** [comment]
Okay it's probably fixed now. I'm really sorry for the unconvenience.

**Comment by tjespe** [comment]
The namespaces are fixed but another error occured:
`Fatal error: Cannot use revivalpmmp\pureentities\entity\monster\Monster as Monster because the name is already in use in /Users/tordjohanespe/Documents/Servere/Minecraft/plugins/PureEntitiesX/src/revivalpmmp/pureentities/task/AutoDespawnTask.php on line 11`

However this was fixed when I removed the double "use revivalpmmp\pureentities\entity\monster\Monster;" statement in AutoDespawnTask.php

**Comment by Sandertv** [comment]
Ah alright, will quickly do that :)

**Comment by TiesGamesNL** [comment]
@sandertv @caspervanneck cant code he is messing up everyting just saying

**Comment by jasonwynn10** [comment]
Please test the plugin and tell us if the issue is resolved

**Comment by NycuRO** [comment]
Resolved, please close.
