### ISSUE TITLE
Plugins crashes players when they join

### ISSUE THREAD

**Issue by ElectroGamesDev** [RevivalPMMP/PureEntitiesX#448]
## Required Information
  __PocketMine-MP Version: 3.19.0
  __Plugin Version: Dev #326 (Latest Verified Version on Poggit)
  __Other Installed Plugins:__ 

## Steps to reproduce the issue.
1.  Join the server

## Description
When ever a player joins the server, they get kicked instantly.
  

Replace this line with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)

`[21:49:05] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\ItemBlock::write()" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/MobArmorEquipmentPacket" at line 58
[21:49:05] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket(127): pocketmine\network\mcpe\protocol\MobArmorEquipmentPacket->encodePayload()
[21:49:05] [Server thread/CRITICAL]: #1 plugins/PureEntitiesX_v0.6.7/src/revivalpmmp/pureentities/components/MobEquipment(629): pocketmine\network\mcpe\protocol\DataPacket->encode()
[21:49:05] [Server thread/CRITICAL]: #2 plugins/PureEntitiesX_v0.6.7/src/revivalpmmp/pureentities/components/MobEquipment(278): revivalpmmp\pureentities\components\MobEquipment->createArmorEquipPacket()
[21:49:05] [Server thread/CRITICAL]: #3 plugins/PureEntitiesX_v0.6.7/src/revivalpmmp/pureentities/entity/monster/walking/Skeleton(61): revivalpmmp\pureentities\components\MobEquipment->sendEquipmentUpdate(object pocketmine\Player)
[21:49:05] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/entity/Entity(1961): revivalpmmp\pureentities\entity\monster\walking\Skeleton->sendSpawnPacket(object pocketmine\Player)
[21:49:05] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Player(1112): pocketmine\entity\Entity->spawnTo(object pocketmine\Player)
[21:49:05] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(310): pocketmine\Player->doFirstSpawn()
[21:49:05] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/network/mcpe/protocol/SetLocalPlayerAsInitializedPacket(45): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)
[21:49:05] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[21:49:05] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)
[21:49:05] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[21:49:05] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Player(3311): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[21:49:05] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[21:49:05] [Server thread/CRITICAL]: #13 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 142.160.17.84 57591, object raklib\protocol\EncapsulatedPacket, integer 0)
[21:49:05] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[21:49:05] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[21:49:05] [Server thread/CRITICAL]: #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[21:49:05] [Server thread/CRITICAL]: #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
[21:49:05] [Server thread/CRITICAL]: #18 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1617832145.0873)
[21:49:05] [Server thread/CRITICAL]: #19 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
[21:49:05] [Server thread/CRITICAL]: #20 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
[21:49:05] [Server thread/CRITICAL]: #21 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[21:49:05] [Server thread/CRITICAL]: #22 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
[21:49:05] [Server thread/CRITICAL]: #23 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)`

**Comment by supercrafter333** [comment]
Yes, that's true

**Comment by supercrafter333** [comment]
I'll try to fix it

**Comment by supercrafter333** [comment]
I've fixed it: https://github.com/supercrafter333/PureEntitiesX

**Comment by ElectroGamesYT** [comment]
> I've fixed it: https://github.com/supercrafter333/PureEntitiesX

Thank You!

**Comment by ElectroGamesDev** [comment]
> I've fixed it: https://github.com/supercrafter333/PureEntitiesX

Still crash,
`[23:32:43] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\Sword::write()" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/MobEquipmentPacket" at line 55`

**Comment by supercrafter333** [comment]
On my server it work's. Please send the full error.

**Comment by Amitminer** [comment]
Yes this problem with me

**Comment by 95CivicSi** [comment]
Closed via #449

**Comment by ElectroGamesDev** [comment]
Fix this aswell,

Crashdump:
`PocketMine-MP Crash Dump Fri Apr 16 04:51:02 UTC 2021

Error: include(phar:///home/container/plugins/PureEntitiesX_dev-351.phar/src/revivalpmmp/pureentities/data/MobTypeMaps.php): failed to open stream: phar error: Cannot open phar archive "/home/container/plugins/PureEntitiesX_dev-351.phar" for reading
File: pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader
Line: 138
Type: ErrorException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PureEntitiesX v0.7.0

Code:
[129] 	 * Called when there is a class to load
[130] 	 *
[131] 	 * @param string $name
[132] 	 *
[133] 	 * @return bool
[134] 	 */
[135] 	public function loadClass($name){
[136] 		$path = $this->findClass($name);
[137] 		if($path !== null){
[138] 			include($path);
[139] 			if(!class_exists($name, false) and !interface_exists($name, false) and !trait_exists($name, false)){
[140] 				return false;
[141] 			}
[142] 
[143] 			if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[144] 				$name::onClassLoaded();
[145] 			}
[146] 			
[147] 			$this->classes[] = $name;
[148] 

Backtrace:
#0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(138): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[242] include(phar:///home/container/plugins/PureEntitiesX_dev-351.phar/src/revivalpmm, string[95] phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/Base, integer 138, array[2])
#1 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(138): include()
#2 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[41] revivalpmmp\pureentities\data\MobTypeMaps)
#3 (): BaseClassLoader->{closure}(string[41] revivalpmmp\pureentities\data\MobTypeMaps)
#4 plugins/PureEntitiesX_dev-351.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(74): spl_autoload_call(string[41] revivalpmmp\pureentities\data\MobTypeMaps)
#5 pmsrc/src/pocketmine/scheduler/TaskHandler(137): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 3601)
#6 pmsrc/src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 3601)
#7 pmsrc/src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 3601)
#8 pmsrc/src/pocketmine/Server(2389): pocketmine\plugin\PluginManager->tickSchedulers(integer 3601)
#9 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
#10 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
#11 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
#12 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#13 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
#14 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.19.0 [Protocol 431]
Git commit: b307cd0aa15b76cfe41d2a649d14b3aa6fb78f64
uname -a: Linux e55e3ebe-16c9-4ce4-88d2-83274459839f 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64
PHP Version: 7.4.14
Zend version: 3.4.0
OS : Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.0@cf7998124d1050b83d7d985447fefd630e09c1a2
- daverandom/callback-validator unknown@unknown
- pocketmine/binaryutils 0.1.13@0abee38d4e2861621f262c79a2a3d699d8a697f4
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.1.2@9757928424652393b178a3760073113aa7c9911b
- pocketmine/log 0.2.1@830b44a2cf96ef703c550abe64302f230231ca49
- pocketmine/log-pthreads 0.1.3@e477ecf6ec214fdd4415ea1da3fdd9d73bf699ea
- pocketmine/math 0.2.6@43057cb8c179a9859677b496a788db922fd5cfc3
- pocketmine/nbt 0.2.18@9f82ca4d7f97fcd9a566e44b63c4f18a7657ae82
- pocketmine/pocketmine-mp 3.19.0@b307cd0aa15b76cfe41d2a649d14b3aa6fb78f64
- pocketmine/raklib 0.12.11@9cce458b8bfde3e4dfdbf70c659fc7b7fe26b5c4
- pocketmine/snooze 0.1.5@70b5e7937a06878dd321a3182ceb76d56298f2cd
- pocketmine/spl 0.4.2@6b08b7cf8c4afa17139c9a1b3bf1b408531de161

Loaded plugins:
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
Disguise 1.0.3 by  for API(s) 3.0.0
DevTools 1.14.1 by PocketMine Team for API(s) 3.13.0
Rewards 3.0 by Wertzui123 for API(s) 3.0.0
cucumber 2.0.0 by adeynes for API(s) 3.2.0
AutoClearLagg 3.1.0 by Twisted for API(s) 3.0.0
VanishV2 1.17 by superbobby for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
StaffChat 1.1.4 by Thunder33345 for API(s) 3.0.0
XGTAntiXRay 1.0.0 by XGDAVIDYT for API(s) 3.14.1
TimeCommander 1.0.2 by TheDeibo for API(s) 3.0.2
AdminTrollV2 1.0.0 by Rushil13579 for API(s) 3.0.0
Sudo 1.0 by ErikX for API(s) 3.13.0
BlazinFly 1.8.7 by iiFlamiinBlaze for API(s) 3.0.0
RedstoneCircuit 2.0.0 by tedo0627 for API(s) 3.6.0
KitUI 1.3.6 by Infernus101 for API(s) 3.4.0
HealthTag 2.0.2 by Shelly7w7 for API(s) 3.0.0
PiggyCustomEnchants 2.4.0 by DaPigGuy for API(s) 3.19.0
ARQuest 0.2 by phuongaz for API(s) 3.9.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
BackupMe 1.0.3 by Endermanbugzjfc for API(s) 3.0.0
SimpleReplies 1.0.2-1 by jasonwynn10 for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
Wilderness 2.0.0 by  for API(s) 3.14.0
MultiWorld 1.5.2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
CrashFixer 1 by TutoGamerWalid (wiligangster) for API(s) 3.7.1
CommandDisabler 1.0.0 by  for API(s) 3.14.0
CustomAlerts 2.1 by EvolSoft for API(s) 3.0.0
PiggyCrates 2.0.9 by DaPigGuy for API(s) 3.2.0
PlayerJoinSettings 3.0.0 by Anders, wode490390 for API(s) 3.0.0
Tebex-PMMP 2.1.0 by Tebex Limited for API(s) 3.0.0
BadWordBlocker 1.2.10 by survanetwork for API(s) 3.0.0
Slapper 1.6.1 by jojoe77777 for API(s) 3.13.0
CrashTransfer 1.0.0 by Xenophilicy for API(s) 3.0.0
McMMO 1.0.0 by AkmalFairuz for API(s) 3.0.0
KeepInventory 1.0 by KhoaGamingPro for API(s) 3.0.0
WorldBorder 1.0.0-3.0.0 by ArceusMatt for API(s) 3.0.0
InvCrashFix 0.0.1 by  for API(s) 3.14.0
PocketVote 3.0.2 by ProjectInfinity for API(s) 3.0.0
EconomyLand 2.1.2 by onebone for API(s) 3.0.0
WorldGuard 1.1.92 by MihaiChirculete for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
CapsLimit 1.1.1 by deot for API(s) 3.0.0
Netherite 1.1 by Wertzui123 for API(s) 3.0.0
ScoreHud 5.2.0 by JackMD for API(s) 3.0.0
PlayerVaults 3.3.0 by  for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.0.0
Elytra 1 by ArchonKlaus for API(s) 3.0.0
PureEntitiesX 0.7.0 by milk0417, RevivalPMMP for API(s) 3.19.0
CombatLogger 0.0.6 by Jack Noordhuis for API(s) 3.0.0
GlobalMute 1.0.1 by Shelly7w7 for API(s) 3.0.0
SocialSpy 1.0.0 by superbobby2000 for API(s) 3.0.0
SellAll 1.3.0 by AndreasHGK for API(s) 3.0.0
AntiInstaBreak 0.1.2 by dktapps for API(s) 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
VanillaCoordinates 1.0.0 by Shelly7w7 for API(s) 3.0.0
AuctionHouse 1.2.5 by Shock95x for API(s) 3.0.0
KygekTagsShop 1.0.0-beta.3 by Kygekraqmak for API(s) 3.0.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
ChestShop 2.4.0 by MinecrafterJPN for API(s) 3.0.0
CustomAnvilUI 1.0.0 by DaRealAqua for API(s) 3.0.0, 3.1.0, 4.0.0
EconomyLand-DisbalePvP 1 by sero583 for API(s) 3.0.0
TempRanks 0.6.9 by Heisenburger69 for API(s) 3.9.0
BossPlugin 3.21 by HmmHmmmmm for API(s) 3.11.0
essentialsTP 1.2.2 by  for API(s) 3.0.0
DevKit 0.1.3 by Manxy for API(s) 3.0.0
EC-TableUI 1.1.2-pre by  for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfWlz3Lay6F/BGZ96R741nBly9jkllxVJjn1ixbqSHOe9MOUCSXCGEbdw0eJU/vvtboAkSMnS
SJ7ceh/iLCZBoNEbeiOI+aPnJ1nEi89XIsuDJO6tJv1eEUSitzJn5mI6Wcxm1mBqTq0FPChT9Whh
DczxwjRH5my0sOYzeBbyvDjOsiTrrf7oFbcpdOvR/fGNK2AcwO73IpHnfI2PgtgNS0/spRuerYbD
4SaJxNBN4oIHsciGaViugzgfnpaZOI6LoAhE/vNnT1wZ46k5wEHDPHOHmbgKrniYRlE6TKGrUF2H
Hi/48CRxLgCRE57mMCR9uWI+D0LhsSJhSSpilheZ4NGKITwmENkVO+RxnBTyObXzzN0EV4LZvacj
afcY8JfBLF4Qr4EBfhmGbwAH4MBXKD9N3EtRnMC1cXIqKb0SsZfAdPQkgidDF7idhwn3hOTDdzwX
h9j2ntqQWpxMTRRhlycDAQAhdANpjxegExl34fqX3osReybAPQAEMmgG2HZZBGFu2x/xr9VKtNTl
LY+9EEYFcSHWImNWH+UFbPzFmli/sl0rUA19Of2V7Vo2fVZRgcwElcr47S/Wry+Bxy/Mb+RnxQgC
Zj0fmDUBYJ1W4xWOoIY9xZ6J+SvTlp1t6+vOtnHh2ba28gitMdu7D/gfbpjkMPzPbwI+Yd9qLQqe
Xw4PyiI5T/l1fAF3e3PkRp6Gnzk0IxM+uzwMvwnPqZIN/qcJJnc3witB04c4caX15ngOCDwwB+Js
2y2kjVdJfFbG9YoZz0YmzTzbZubz6m7PnC8767Tuadsaksar7L7Z5vfPJoU0PKW/TngMfiDbm00n
D09VY2W8imARXmzQlr4VPCscwYu7ky/un/xcZODh9qzxokuaRMu2W3gZr4rAbebO786zfHgecJid
eeQTCViuVXP0IAxzuXwIxmmWuOBNk0wBMx8GNl3MvgIsL4CZCoh1P5DG7u1ZS/MrcD5/BkMJ66N0
i73E+U24RXfB95lqv8cFnIBw3yfrNfZSi8yc/cq6FljzAXcfVmZA0jJ+lJax1aUll9ySACYSwJ5p
0kr8vQwyURmAufkUJ/FVFCgs6f36Z78n/g6dHguddhbNALvl/J+D+CoJr0QExBNjPRCxW/Sq59DW
QhAeuIknUEymtYSndsH+C8gOkTPXGyC72IhMsCBnnBFCyC9ECkaa45EaQTdmNfx1yjMeKb1m/4w5
RNjYwdJ7j+vemSjKLGZOkoT0ZKKeDOluSndp6YSBy/wydlF7WOPECfzLP6jvjPraxT9TXmzYPvtn
sQly45UPbNA7/5s6z1XnwN+T/f+xv89iiGYVsIV6Dj2UelI3NXrZPPX3/kGc+SxugrxQk/RBvcJc
vGTgWNg/0NhmPsSbD/SBeDQo7n0uEZqM6intQvGMnhNCE7N++ifdI7PpYqxjGolik3idWexeEjeK
5dk9idFeLK7ZmfBDQTzXOfjSeLWG9U7A9u4ON14F+XnBwajvVchPNOQJxmrVGrUn+TqZdsiY1fd0
O69vlWyJ8yL/5VcUN8KVYFB4vT//DvL/DvL/DvL/DvL/DvL/DvL/DvJ3HuT3e2sBQ3mI4SNFeRBd
6mAAHwd42ZRie+OBuRyMsL0MQg/rruNJvxfkaPV6KwpnIFTNkiJxIRpcTcYmTBJgKOuMR3PXG3Fu
Tp35zPXFxPQsPpssPXPijDmf+c584c8mALtUuLwP4vKGielUjIUjDHPmLo2JKybGYuFZxmJszSeT
6XIxXvpsMjCng5EBIaRBNEGsCZwcGR+dMi5Kdn5yyi42JfsPj5m1YKPpyhqtJnP28eKQWSPLZDeL
2WeaG+uUq958AADx9gs4NCJ7QlTD089JXqEGDXQTqhs3idIEZPk5DJyMZ2AvkbHc2wAzMjH8LU9i
A/qo2N4cmIPRa9efL5cL8IKeOZqOnMXYm3vLxXQymfvC92bjkRgtXZNbAN7jIAcwgUk0RKfgcPfS
ACsdgNnHRA3Ydhkn1/Fr9Tei2wjfCWKe3ZLWQ9cRzG2OX4+4I8R44U2EtZiZM8v0rZnlzpfc4mNv
tlx6Cz5bzv1JG9S9kwMtg/Hr2WS+mE9gzGzmuJzPxXSxmELcJBZT1xq71lQs3OmUqLk/RlC4Wa+X
8+l8aS0m1mQ2tcbLsWPOF3w8n41G87Fpgr7M3eXSNJ02pDBZEwRrYL5ejEfOZMIt11/OhD8fjWFm
JHg2GY8s34L/jU2XT5Z3IBhpQea+YtT4tZjM58L1Z8K1zInveZOJORXc9PgYbpbefOz4wC3B26Ai
yDYUNrPXMOl07joLF7wcBwEvZ/O5M1nO+ByU2Vlalu9NXd8dt0HETlHRs3i99BcWIOzNfZCJ6y35
dDYTk4kzG7sT31zw+Ww652LRYW5zaURpvYJfP2E5asAyfgm6LfkCOJmvly6sx+nCWTi+B6t04vme
A7x2Z9Ol784dUGJr5kzdDpg8TpIvQrF3+no+cqZivhzP+Wi2mC88DywkH5tArQDcvOnMWi58y/U6
QNKQIExAW2bOaOHMXX/hTrjPzTnkd+6Smw4IxnQmo8V0bHrCnJm9P+tMm9bmmySLDk7fafavaun3
GqMHKkCrH2KyTZLlmI78lvyWiDn+QTPK0wAbxyCnEd6LmDuQgPdW4JbAHnoiBTOC4+BZnvjFkd6A
8QVM0kC0bYVEfYGlAkzZwTx/OL/49OHs/RE0XQsnDwqhMqWjIF+XQS40WuqmNjGwUFvE6ASMnk/A
QcZzfsnfHdl2NbH0r1thL64ukiTMdeyrpjb2Jljmtiwal8UuBI9aAjHHzyeoQgDoaVBRlJxfHJxd
fDxt0bEpijQHzwz+blM6A7D0mssd1jCA2jNxzTNPJ7Zq0Wm9o3SfRFZ8KQPTGvd2JLMGom0rFLaT
2T20NrCGCtQQaXVLt4wckWnE1k06tRbR0aIXHMJtDE70oRWmQo6tqFXwbLtCwLYPG1SeSq+CNqyp
AWIxLzoMIU14z9drjeJ2e1vIZpfsi+sgL4C2Hcm4kOBsG1NKF5EIAQmZw+k4PZV+heZBfhuW0cnh
sA0PmPETj4N885Ol8aFu6qzpeZsDeZmKzEkc53ZXTGgg2naFRHO1jYX6lGShB9lPgeXYhqJWc1uf
x4NFR5/DoAx3RpKEZtvXiEEqMegu3i3N1AnkGH4gQk+PFqq0poD0H2IZkHU2bFELTDkvuO8fbrjO
kaatI+TBpKPnmzKGkG88Hk+mu2KKDhNyxAoV7fI5mi6BHiUiP1VMacABF37+/uIgLoKfz/itxge9
teuAOyv+5++PDn56d/R/L9q+Cz3dM/lQQ7RtDY/t/fFFEIlDSFV47LVMd7u9S5bVFbA4EoGTdIRr
PVu4+uTbqDqZZA+0+SJLwrBliVrNj4jnrMw3QWiOISPZlZ5qIMESa7hsL6Lz0kv0ZYe3HULaZBxn
weXPO4uOCJpt5zDt9jh/F/IvQfwm1NdJ09bGfjHoeIUgeBPyKAhiHCF2JYk2VNuu0dEutyHtTHh5
kcTiMMjcMihasV37ySNRD/jUZDSz2onF7PkEZmr6bRfMD0HxUc+I5H03H5q1kX4X+yKLy9wcmS28
J8/HWwNp24TE9nr2VvCw2FxwPQZr2roC6Jit840Iw9v59XxnwUcF0LZrJLan5TRYr28PS5BhdBy7
Gx4XeuJw39M2fZOugh1xGPR92Q5EqKz33ERJAbTte7C5t/EZTriaZHgPOEo0Ds7+uxS5vvCqFp0f
d6SdbsokXvMvLW48xoy6TPAAVyrAtk1YqL+2kfixm8RJdNsuTGiNOj3TwbxLEax1B/7blfYqcLYt
JAYA07Zb2Dxu9rl7WaYnem2ibnq4NtE7Rl8PHt8p119+891dEdUBC7Ze4dNcbeWDgygNxZlIQ1Xs
rZxxq/1OmGR0Khi/8TyJr2/j2BztikANJAS/OjpP8NZY4xdZtzDTam7TBtbUcETBOxp5+EW4m9OT
I3GFA34KboLLw//3IKVPSetdhJ5GHkC3bUciV8jCTQfVp9ocDe9hCxTmg3Qbi1xnjdb4sJfvxPnP
FnNU/g7oQxJYT2zbzfaixwR8UoZFQDmdRoPW2BbudLCVWHFL+W1Z5OVlANeXkKYGl/mu1Lol6wgx
pfQXdFrH+lvkrAECDh1mPN+8CW5aSZDW2OJQJ/spi+R7GJB9wtckbA9EFKx5vMZE+mWLH/Pn53k6
UNtuENt+kauE6ijIcfYWmZ0nD2dJu9LoplJjjUZguzpYPIEwChEOYEwrYGo1txdpR4DHV0l4Dlju
Snf1mbHy2MJji4LN9fX1QABOCH9QXDaxYcYLcTcmlK1dM7TcIhZ88luMe6PQr8eHhFnr5tvjQQJD
ceBpyG9F9p8kiM9FUQSwNnTW3H3YKbl3o+UDjBSw13XiiclyNF7uzEdL0LgHpIvUEwo1whE3xunJ
yalepWkaOxp+p9aMPdn7IAp2WHH+rrx1M+6DW2ref6Avlq2yhLZd2OiBIfa+CxFK1goeWw+6MYg5
6paTsyseiwJcxeXuCsoAE8IN7gFUz5GYYPDYwWwrtVal1gEBHShMhy/awCneDHmatlhRtbR5MOva
sq+8r/yWAlAuZ372+6IGpWFFROVwLzIe5/5dn1u3P1ZPFXGSbsA1ujurtmsglZ+tkOncbhV3uScn
H/SQi+4fIergMuLhGx5k5ZedGaAGJIgRkdje8PwgRPouvhJxkWR6Oa/d/mBB8odNwiFCAoN3miW7
oqkF1LZb6GxPHQWA38Hiaymh3npHWsZ9ziNzRZmf8GJnQYSGwrNXHiesIsQKSAXuVHGjRqre2q6f
jDq2ZdepTBBfuTizH9w8JZeRruanpBB3drNRY9fNd3IZUBbcI/gu9oM4KHZmNjpgK4+IGOnXT6gK
veexd7csRK1dX7+DupBednpCjSgEdOoikcJtuzX3fckzr7vkZGP3deKyQ99JsOHB4Qar7KEovrH+
dadq3xDbmce2Gxz162cszA7koQYMNbzMxKnIolY8W7e1uTPp1tFmkzdvRiP2f9hfpOif5QSg1BVG
2uUzWEFjtf31Eg4GCDzNKV7Vg4O6rasjnTDIE8nu0rlqUggAtPkfVfMfBX6SFbTsVNPWIeB/cwNQ
jcQutgA1FGHYivtf35b6uq6b2sVsq+tB/8Pdy5OjXZErodl2NXtztZWLoTztJ16Gxd2cUjW33cz4
gSLJ6NtdZUozX9HMVRpZ4/E4ObCsOns36qauNTHN+8zJ01xJs4zvWts3nL5RyzEQ7EOwfRUkZX56
bFTtva9YGrm5Q0P7W+1MtacD4p9zIdoBETY8EqRT4vc2yYIvCumd5NM6UNuWmDwlNjoOb4uM61GD
bHigegmR6yaJfwh5uTMy5KRPePHZ+tC1raT6B7B6cDrvCiQKwsvRhDaYncmvmqgssqtXnw98KaWj
+eQdWRqu7c/LVMnW4YX8bKVdr22auzH77K5ZZT8mkEdsyiDf3Usn9zKugNq2SwiFhBAVcnX0HhX/
92Hi8PCkbDlKrbG7Es3/vbf4a8IiKtFVtjB6/IVh4gY8PE/1jLlpe8S4tEvju6Krnh4387Rr71tv
RQLOHIT6Z0RVyyPb6A9iLxM8f/v9D39FVtJAx8/FCKH6YhuycNvcuzgv+HcA5lLfWNB+0F5rd/Iu
77LgaXpnkRkH70/fHpBj1e+t6v658lTT2XYby+2libtiw5Af4kIO4s67hXsePqK1f+VCvIvNU9zi
QUnBxVsINURrs7bW3K0tT7vEgWteTm++MdlsbafQSy861XIm3MdN+G0QP9zG3cL28brd7VpcXvB1
Dqinet2u1X63uoWv9btJJY3J+O8Rv9wdA7RSXgPetlv44Ue6NaZPDfk0sMM21fVbQ7xrbYJrNevM
mQCxXZ3gYXF7GtyI8EhcffkrDFt7hupdosTuygIbtyVjgC85gkoR1GDNiQEbkRcd3WjaHtlahm96
6CWPyP5z+uNfQXqNClCtYfVUHUghDAkKI8nSDX16PWyANa+O46sgvEcLqvZH7N4RPxM8PPi95Hf4
0K8/+5g8iS/9bfadEXrbW3utSGccBTnEMuL06vT+CqPe4YHcIRdZMl2MnyV+KhY+ZPwlbNs+Pnyv
9gQANk95XxqlZzy+zFuvS6u2tiefdd+WvxVBLmKnzCCEnS2ftmPwgey3oa49AVi5CrMnbNpKcvWV
gv7CtGlsFyisjujeRhH8C3/aGZL52PYs7T1kO115gNhNFG1wKtt2Ety3hEg+YylXKA81IvH4qjzH
XAwQvdC1udXcde7WX1Gs0We07c7823wY+UOr1qkaujFnxzOf8PhmZ7VdAvYEi3JoXOAkLdOpNXZr
tJaRZuKv4Py5u/GS6x9/enf07gANxsX2W8jxM2E8BEsUQjJ0cM8BCzDGMOLEuA6+yHq/YXjSJBk8
zgPSfTrZYZBmCSwOqgSsei9O6zt2mMR+sGZ4kpid2fELPKTghGfMXDBztpqMVuNRfUgBdoiSwttv
YcLkQRj4UE5mpElW7FtLa2Jh4/UGaDLCIC/2R3iPJ6KVsYvfd2G50ODuJhDywLF8P4kJDp7sYqhP
ykBO++aM5uY3alC+b04J2Bo4FCWekKD9JAO4dVvi+9gKjPKwyFrdp1epmscLfD9wSwhA9glVeRpF
kWRGrvbB7GNzCOiFBurRvtzsV7flQnhaFzyobv/o+M3Bx/cX2Cp1xvi9FNntPuqN1piBu6kwwutB
yvMcd1vs/xf9AUaVRWLk/EoobK8CcY3yLThwb3+CTTdOcmOg2qouIY/XJUQT+yJeawIJ0n0swcA/
2EjoDNpCan3ZPriN8Mv2FwxVlbmkISXwBc9NQ0WhU+haOgCKwy4ggBGsYhzjmcCj31gSg5YVG14w
V56F54jq6CYPLtgdBUVY50kEI30E0IWZc1/0WYLF/RxBMgeTS3ablJmCxQKfgfwDP6AZQPR4gl14
i4B/FNc1uKEnfKpVs+sk/lfB0H/gCX3A9giPHuOQ5CGGeE6YpJvOsyvTdUYH8A3sGDksga3smLEX
nzb01gGPuAMr6zEAoQ5uAR7g/owQUkRPPiZUwwSmAVLhShTEL09cBa5gGzpqCFsihCw1uxLvSp7b
hg/yTVmAjYkNdRjiitk9uSAZHjKFp6kRZgdhmFwzXIV4pJ7a78OuAs7+G9UB+5BeVF9drhjpKw49
JoVVY+hgN1xNDCQGTEFozi1TrMT+Sr/rxxqyLz5BsgwaAXzlnscykUv20zGBgXvJIsHxXCy0BXhi
oCMQaWCOgCA2RLatgyvoe8XDUrA9NSnYppcIXc4IK0ugbhvAdqz0reAxzf0jfSSNWnWQ38YuHrLE
cJsT6NGAOnwEbpFqV5Rit00GUWEJ0oPueZ/R+mfKTsB66DM8cwUIQXdCvAEjjm1RGYMGYRcJ/JzE
i6cgpoDnTQAaJoANQBJpblwjh7xVCL3zUVexD+pknwXFv4B9RUbDPIHGkVSmM5jtAQ2QjDOL2EJk
GIrSFYHq6ion5cjKOEZxemjLkpSEQLvZ8wEDp6+uWRSsN7CYsUDQ1xefUhzkSJaVaSFbJcOQMRHg
pugi4cKipKNoPLkg+FUSeID2/RigjqDOQYQVgHYNNEXD485kp1rTwFWAB8hu5aKUBVKGTprJdlgH
UVDg2o7Emju3BXCcnUtWj4i50ovS8AuU2nVAnCeNgkV7bUhAlZLlRKEfAIpgkQTu9kEwfiZENWV1
FiaQCMuUrRMQVILLFLUCJ5I1XYNQW7ERUgGzkwmWx8H8f08BRj0P4Y+O+Nvwh+w3JRSU+axRUuBy
BuYDHSnYvQohnLWLFVmAT7QkFHL5v3aAHi0KwgfNBXNL8DwxeB4mboRbkuVNJL5yOaKnqnuLGxei
ibwhR1qtDxfHK3bx9t05e//u5N0FOzg9ff/u+JydHp8xCBx/OD7rM+jELj5Ar2P26e2H98fs9OzD
4fH5+aC7/u9lBiSFQUK+GG0wnc/qbgRZY+JFbWdNYDtEAx6ZFepi4K5naWEJFESTQCXYZlAkpPZr
eib1CyJD9H14GOu1mowgSyBgdRsbLp0RzfEB3Qe6eBowuNsb1UBF6yC0VLgYCUi+IrpSqnJsTQNo
lkjzhlSIeiWt+cv7UVKUjxXla545sCgMNwnVaadke+7nLq0yREeNYmoUmO2IxyXFHTomEJOVoIEv
+5U76KpgpYTSs/o+wJL0Rs3qG7AP0txLdYfAISlDr8YlAP9xHbMG/1wCTgn9FR4AOFK0wmxvyE7c
8Y+kOhJCTZufJVHlZ+Vo1cPQFVOXMFKjJHlHN9g9KtXSjmoDO4kMv2hHNVSK7JVRKgMrGb0x9cDA
B5W8jrCTGkC4E5oVBXAHHh6WOr+HweCvwefBDFd43nFeCjQLxQaktq4CTbRXOFuDVb8SpAwPVDw5
kNhg16/yCdMhd1PGl3mF+yFPsTWIygjcK27uZ1W+gIJkMnmSWDR8xfWiWEkr5q6OQZydKoxoQgMD
4BL87aSW2FEiH3V1GsMitHkSvuxcLSEJS3XUKaOgwXAhMxQ1bVhrozAFIkfkHmAnYwsJJeWYjjA5
RlLYUAfDFD9Vdqxmxs5NoIsMxONjKrgPg3pID+1YbaFfKQcBUdkmCWV06fACMl4MwgnlHM/IZcrF
kG2TSY96Kh2LI+o4U3q2F7qUqkdoVrPbAoH3mWFqAiTh0cRGUSGzYlPTUla7CWEpkcXoUZ3ejWkM
xfg4GBoVWgP2FsJA0KV9iuvY4enHPowFHBxYX9eBB2pPYYK0njV8g+CT4siIuwnGc+KO1nfADjww
VBse+kPIImWG4AnQYTUVTErneKOCaQuxcXoaMD2fuUGjhsElD/vSZuLMn4IYEimg7CIjd5FQDP3x
ND6tIvAmK8QEAwfhKVMIs0zj1FD3nZTnRK3HPPgiakljrF4JGMtxVRwFsbxUHM3pTpaWHPRywE7V
mJBjgRbTapWeKi2hGf2Mr5E6kBaQlachRTKYc0Z4LDuYAZ6hBA/DAGsulETjMZ8iL9jJxUfCNAeS
kGynLBgm7STkZjqZcQwqKxQVpYGjVoQt6r8nnHK9qrKYV8zE7EXFcBtYxPScqZw1l1k26nicJ9Kl
KT0xEZg0WxLa4SaBrBZ1s0peRJWekm3DI4hZzq8qG4r1k6rShM8aPeDg0sEQCF5UJgYwlXXlKlim
RAs0iKKVPIXwjKKXOHHDIGU0Fvh4wm+Bh6gsUXJV5a5o/ZXJJLNlVM/klHljLKpKkl5HuKBCgFQA
+WtUsoRCfZW0y1wVJFxQ+kKaBTXGkGNWLIV4Al/GwDTS5KnlrGZBm83jdR1Oxzgs7LqOftWrVYC6
t3Yj87uDKClRp31pm5WKIytl8Y58Ea5mytpBMHgNUSQNPiPXog0mwmMhs0RHSGCO8FEjqVBI3mBT
aQAJneqHlZOyGvJxopp8WJmMd1FN5fHCMJsA+38flqP70eQZQAL9qBQRkK0G4986NqDdmEMbZerh
jgHNWtDpaDQRFUw1o/XuiCajT7FyWpLIT5GhpJk8lJUp6piqOVTOjsa0SAd4BrPYC7aGhCVv2NPU
NWoODe6ySC3Wax5QRgOGAwJ+KZs0ScuwUkZ1g1af+lQmYoYTUjBspGpZo3XFlbpiVZhJxU9ZyVkp
h4eFJ0qwZLP0F0pegEhTEvAavqG+G/gDFZ2merm1m9MNRGZ+okkEVpkh3/nUPTcJSoZQGeC+u0GQ
EMZxEt9GmCLk+MsFOVCYN6hj3qOes+Y5kUAmi6/XGaSasqakClAyz8ZfILjs0kf4wQr+cPQBz2g2
lBGUvgCNwrWQcShn+CMMOGNOiDcEUNtAq/qC66k5L1VTCucOU0Gg8rlSJvB6eK4w2W49nKL2RGcd
RKgx6olW4OmDfUw3vM9wfwc5rKKOWMD0+gJyaBAhWKAYHYJ8WjkWWS7irYKRerejOZwSojPwbWTF
KmOhAJLk5fNqjjuSlrTqoi6CqLHVyiMhUOxfBQ4oWTSYOCFVwtSgquo5aCZQT/QZKm4+7POU2ZbS
latCqzEoGAC+UPysqgkb1UgWAxMCFWMqi4GVWQjjPQqyAr8GBJE6ECLL8GiBqiRb2jiAp0xk5dl4
GPBcRfAQdXE8A0TdYRAAOCpZrSqhyWegt1joWbFfyHuD/+xT5edXyg0CDF214yYqe79i0TUrUhm9
4/R00ThU/UUCEYwxVxZ4KhWvXv1Qjn2fbyPXT748p6iTUjg8qwGoUo5ZJ1TOSzjIS4YviyDyHcnY
t5lxxd68P7hYWf+e96fLG7M/vhn3rX+b//aEm0hrvIdHILpohvcXI2m05d1k+lIGSLJmr2fA0hag
FwJpqPIUBSlUXwL5urdMnlpfZpX5rsL+rK72k20COODUXHqbklcMM6o3BaA1MhJ88YaMEk1F/VtA
6ARD1fJZazEoLBs0lbSEfgWFyV+YURmTe0nnuVJ2ABxxAohpb2VyTf2Q3gB3GobS4cjVJakk+BC2
ZMpq9vo9cVOIOKdt/as/eocQSehHruNq1+/DwLmhF2J1C/6cU563mlK3DST/HVAU49ZR7vLk6vre
cdUB3XULvguKPZ612rLbtEjoJfuYthi76uewmh5l1kIFQgHcHDUajU38SaZ+D8991zv4QViI1iR+
0Tp0fu217qLWww34vRalEA569M1c03Z++r7FQVwdnlOdJI4/3eXI12J6r+gWmEan3asrpnE3Llo0
nh59aHHfSz7ToG6jFENr5KbN38YBfqb4Rj+hnk7cT3L8LlUb0BzOjidVmPjDA/1eJkAMqFJr+f1g
Pb75/aMW0zZR0uKqPCHp55MW33LCLW8JN1dbRVCwwVqeql+hAk1FciliiLNaNHbUF26Rgjt9rvFz
qVbjLaeRlvos6kuQyi0TU9rOTxwPmv5//vk/5zrcFA==
===END CRASH DUMP===
`


Not 100% sure how it even happened.
